### ISSUE TITLE
SeBuilder changed install directory?

### ISSUE THREAD

**Issue by colinmo** [sschwartzman/newrelic-synthetics-sebuilder#10]
Firefox just upgraded and invalidated my SeBuilder plugins. On reinstall it appears the directory name has changed to SeBuilder3. Is that an across-the-board change that will need the readme updated?

**Comment by sschwartzman** [comment]
Where did you download SeBuilder3? I know that SeBuilder is getting re-worked to be compatible with the newest versions of Firefox, but I don't know when it will be released (or if it has already).

**Comment by colinmo** [comment]
In the about:addons address I searched for Selenium Builder. Looks like it's an updated version that's compatible with new Firefox.

**Comment by sschwartzman** [comment]
When I install that version, I can't find the add-on anywhere to run it. Says it's version 3.0.5. Is that the right now and if so, how are you running it?

**Comment by colinmo** [comment]
Tools > Web Developer > Launch Selenium Builder
Also Option+Command+B on OS X.

Version 3.0.5 is the one I'm using also.

**Comment by sschwartzman** [comment]
Thanks for letting me know. I added to the README an explanation of how to use the old version for now, as the new one is still actively in development to get it closer to parity with the old version.
