### ISSUE TITLE
TaskTimedOut

### ISSUE THREAD

**Issue by akemner** [sschwartzman/newrelic-synthetics-sebuilder#13]
I got the plugin functioning and it produced a script but running Validation against the script produces this error. attaching the script to this issue

TaskTimedOut: Task timed-out waiting for element to be visible using: By.cssSelector("input.site-masthead-search-btn.submit")

[www.usatoday.com_search.js.txt](https://github.com/sschwartzman/newrelic-synthetics-sebuilder/files/224399/www.usatoday.com_search.js.txt)

**Comment by sschwartzman** [comment]
Hey Al,

This one is probably not something I can fix via this plugin, as it's due to the slight differences between the Se-Builder engine and Synthetics's engine. Give me a shout off-Github and we can see about getting your script to find the element on your page.

Thanks,
Seth
