### ISSUE TITLE
Failure on verifying plugin

### ISSUE THREAD

**Issue by dannyhu04** [sschwartzman/newrelic-synthetics-sebuilder#15]
After installing builder and plugins, upon verification I get the following
![verify](https://cloud.githubusercontent.com/assets/21689710/18179150/cd297838-7046-11e6-9545-c62400c616bb.JPG)

**Comment by sschwartzman** [comment]
Which version of the se-builder are you using?

**Comment by dannyhu04** [comment]
2.3.5

**Comment by sschwartzman** [comment]
Can you post a screenshot of the folder contents where you installed the plugin?

C:/Users/[you]/Appdata/Roaming/Mozilla/Firefox/Profiles/[your_profile]/SeBuilder/plugins

**Comment by dannyhu04** [comment]
![image](https://cloud.githubusercontent.com/assets/21689710/18184614/729d84e0-705f-11e6-8e53-32d740522b87.png)

**Comment by sschwartzman** [comment]
Sorry, I meant a tree view, so i can see all of the files in the subdirectory.

**Comment by dannyhu04** [comment]
Here you go.
![image](https://cloud.githubusercontent.com/assets/21689710/18185162/e8fe17e2-7061-11e6-9e4a-1f0afea7f4a3.png)

**Comment by sschwartzman** [comment]
Hi Danny, did we work through this issue via email? Assuming so, I'll close this ticket.
