### ISSUE TITLE
switchToFrameByIndex translating to string instead of integer

### ISSUE THREAD

**Issue by terryllowery** [sschwartzman/newrelic-synthetics-sebuilder#17]
When using SE builder the switchToFrameByindex() is translating to a string in double quotes. This doesn't appear to work in New Relic synthetics. 
Example code:

.then(function() {
  log(85, '$browser.switchTo().frame("0")');
  return $browser.switchTo().frame("0"); })

I had to switch this to:

.then(function() {
  log(85, '$browser.switchTo().frame("0")');
  return $browser.switchTo().frame(0); })

**Comment by sschwartzman** [comment]
Nice catch! I tweaked the script to record that as a number. The latest version in the repo has the fix. Can you try  it out?

**Comment by terryllowery** [comment]
Sorry I had been pretty busy but we will take a look at it in the next couple of days.
