### ISSUE TITLE
Asserting text box value is empty results in unexpected ) token 

### ISSUE THREAD

**Issue by byngj123** [sschwartzman/newrelic-synthetics-sebuilder#19]
Hi,
I have just been testing this plugin and it is really great! However, I have run in to a small bug when I try to assert that the text box is empty, the resulting code from the plugin is `if (value != )`. This then throws an error when verifying the script in New Relic of `Unexpected ) token`.

I can get around this by going through the code and adding '' to create `if (value != '')` but it would be great if the plugin could do this for me. It only happens when its an empty value.

I would try using the assertElementPresent test but that doesn't seem to be supported in New Relic.

Cheers,
James

**Comment by sschwartzman** [comment]
Hi @byngj123 - just cleaning up old issues. Because this is being sunset in favor of Katalon Recorder, I will not be fixing this bug - I actually tried to recently and it wasn't that easy. Thanks for letting me know though!
