### ISSUE TITLE
Adding New Relic

### ISSUE THREAD

**Issue by jarsh88** [sschwartzman/newrelic-synthetics-sebuilder#20]
Having some issues, I downloaded the patch, but cannot find this:
Win: C:/Users/[you]/Appdata/Roaming/Mozilla/Firefox/Profiles/[your_profile]/SeBuilder3/plugins

**Comment by sschwartzman** [comment]
Where in that tree did you not find any subfolders? Are you replacing [you] and [your_profile] with whatever is found at those levels?

Also, have you successfully started the SeBuilder plugin on your browser yet? It may not create some folders until used the first time.
