### ISSUE TITLE
Timed-out waiting for element to be located

### ISSUE THREAD

**Issue by Anubat** [sschwartzman/newrelic-synthetics-sebuilder#22]
**Problem**: I'm getting this error while validating a **Scripted Browser Monitor**:
TaskTimedOut: Task timed-out waiting for element to be located using: By(css selector, *[id="tripCalcBtn"])
It is giving some DNS Server error when doing browser.get for my link (https://tpyhouftst02.sl.bluecloud.ibm.com/hr/flight/scheduling/)

Here is my basic script that is not allowing me to proceed further:

======================================
/**
 * Script Name: test1
 * 
 * Generated script for New Relic Synthetics
 * Generated using se-builder with New Relic Synthetics Formatter
 *
 * Feel free to explore, or check out the full documentation
 * https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-monitors/writing-scripted-browsers
 * for details.
 */

/** CONFIGURATIONS **/

// Theshold for duration of entire script - fails test if script lasts longer than X (in ms)
// Script-wide timeout for all wait and waitAndFind functions (in ms)
var DefaultTimeout = 60000;
// Change to any User Agent you want to use.
// Leave as "default" or empty to use the Synthetics default.
var UserAgent = "default";

/** HELPER VARIABLES AND FUNCTIONS **/

var assert = require('assert'),
  By = $driver.By,
  browser = $browser.manage(),
  startTime = Date.now(),
  stepStartTime = Date.now(),
  prevMsg = '',
  prevStep = 0,
  lastStep = 9999,
VARS = {};
// Uncomment and use this if you're running Se-Builder 2 and used Manual Entry variables.
// If you don't know what those are, fuggedaboutit!
// VARS = {{scriptManualEntryData}};

var log = function(thisStep, thisMsg) {
  if (thisStep > 1 || thisStep == lastStep) {
    var totalTimeElapsed = Date.now() - startTime;
    var prevStepTimeElapsed = totalTimeElapsed - stepStartTime;
    console.log('Step ' + prevStep + ': ' + prevMsg + ' FINISHED. It took ' + prevStepTimeElapsed + 'ms to complete.');
    $util.insights.set('Step ' + prevStep + ': ' + prevMsg, prevStepTimeElapsed);
    if (DefaultTimeout > 0 && totalTimeElapsed > DefaultTimeout) {
      throw new Error('Script timed out. ' + totalTimeElapsed + 'ms is longer than script timeout threshold of ' + DefaultTimeout + 'ms.');
    }
  }
  if (thisStep > 0 && thisStep != lastStep) {
    stepStartTime = Date.now() - startTime;
    console.log('Step ' + thisStep + ': ' + thisMsg + ' STARTED at ' + stepStartTime + 'ms.');
    prevMsg = thisMsg;
    prevStep = thisStep;
  }
};

/** BEGINNING OF SCRIPT **/

console.log('Starting synthetics script: test1');
console.log('Default timeout is set to ' + (DefaultTimeout/1000) + ' seconds');
console.log('Variables set in this script: ', VARS);

// Setting User Agent is not then-able, so we do this first (if defined and not default)
if (UserAgent && (0 !== UserAgent.trim().length) && (UserAgent != 'default')) {
  $browser.addHeader('User-Agent', UserAgent);
  console.log('Setting User-Agent to ' + UserAgent);
}

// Get browser capabilities and do nothing with it, so that we start with a then-able command
$browser.getCapabilities().then(function () { })

// Step 6
.then(function() {
  log(6, '$browser.get("https://tpyhouftst02.sl.bluecloud.ibm.com/hr/flight/scheduling/")');
  return $browser.get("https://tpyhouftst02.sl.bluecloud.ibm.com/hr/flight/scheduling/"); })

// Step 7
.then(function() {
  log(7, 'clickElement "tripCalcBtn"');
  return $browser.waitForAndFindElement(By.id("tripCalcBtn"), DefaultTimeout); })
.then(function (el) { el.click(); })

.then(function() {
  log(lastStep, '');
  console.log('Browser script execution SUCCEEDED.');
}, function(err) {
  console.log ('Browser script execution FAILED.');
  throw(err);
});

/** END OF SCRIPT **/

========================
Please provide me a solution for this issue.

**Comment by sschwartzman** [comment]
@Anubat this issue is not one you're having with the script writer, but with Synthetics itself finding the element you're looking for. You'll need to debug in Synthetics (using "inspect element" in chrome might help show you options for what to label this element). You can also check with the [New Relic Explorers Hub](https://discuss.newrelic.com/) for suggestions on what to do.
