### ISSUE TITLE
unable to find the SeBuilder/plugins on MAC

### ISSUE THREAD

**Issue by MichaelOsowski** [sschwartzman/newrelic-synthetics-sebuilder#7]
I follow the directions but I am unable to find the SeBuilder/plugins.  I install 2.9.0 of Selenium.  I am unable to install the formatter.  
![screen shot 2015-06-25 at 4 46 09 pm 2](https://cloud.githubusercontent.com/assets/13055273/8365234/caf98230-1b59-11e5-8f0c-63d32fffdea6.png)

**Comment by sschwartzman** [comment]
It's not Selenium that you want to install, it's se-builder, which is a different IDE. http://www.saucelabs.com/addons/selenium-builder-latest.xpi

**Comment by MichaelOsowski** [comment]
Thank you Seth. 


Michael Osowski
Technical Account Manager
New Relic <http://www.newrelic.com/>
mosowski@newrelic.com <mailto:mosowski@newrelic.com>
m 610 704 5536
docs.newrelic.com <https://docs.newrelic.com/>
